bot/urls.py

from django.conf.urls import url

from .views import CommandReceiveView

urlpatterns = [
    url(r'^hook/(?P<bot_token>.+)/$', CommandReceiveView.as_view(), name='command'),
]

codes/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('coupons.urls')),
    url(r'^coupons/', include(('coupons.urls','coupon'), namespace='coupons')),
    url(r'^signup/', include(('coupons.urls','signup'), namespace='signup')),
    url(r'^bot/', include(('bot.urls', 'bot'),namespace='hook'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        #path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

coupons/urls.py
from django.conf.urls import url
from .import views
urlpatterns = [
#url(r'^apply/$',views.coupon_apply, name='apply'),
url(r'^$', views.index),
url(r'^index/', views.index, name='index'),
url(r'^show/', views.show, name='show'),
url(r'^activate/', views.activate, name='activate'),
url(r'^signup/', views.signup, name='signup'),
]

coupons/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Coupon(models.Model):
	code = models.CharField(max_length=50,
							unique=True)
	valid_from = models.DateTimeField()
	valid_to = models.DateTimeField()
	discount = models.IntegerField(validators=[MinValueValidator(0),
												MaxValueValidator(100)])
	active = models.BooleanField()
	client = models.ForeignKey(
		'Client',
		null=True,
		blank=True,
		on_delete=models.CASCADE,
		)
	shops = models.ManyToManyField('Shop')
	promotion = models.ForeignKey(
		'Promotion',
		null=True,
		blank=True,
		on_delete=models.CASCADE,
		)

	def __str__(self):
		return self.code


class Client(models.Model):
	first_name = models.CharField('Имя', max_length=50)
	last_name = models.CharField('Фамилия', max_length=50, blank=True, null=True)
	phone = PhoneNumberField(verbose_name='Мобильный', null=True, blank=True, unique=True)
	email = models.CharField('E-mail', max_length=50, blank=True, null=True)
	birth_date = models.DateField('День рожденья', null=True, blank=True)
	active = models.BooleanField(default=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	telegram_id = models.IntegerField(null=True, blank=True, unique=True)
	def __str__(self):
		return self.first_name

	def is_active(self):
		return self.active

class Shop(models.Model):
	name = models.CharField(max_length=50)
	def __str__(self):
		return self.name
		
class Promotion(models.Model):
	name = models.CharField('Название', max_length=255, blank=False)
	discount = models.IntegerField(validators=[MinValueValidator(0),
												MaxValueValidator(100)])
	description = models.TextField('Описание')
	text = models.TextField('Сообщение', blank=False)
	shops = models.ManyToManyField('Shop')
	valid_from = models.DateTimeField()
	valid_to = models.DateTimeField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

coupons/forms.py
from bootstrap_datepicker_plus import DatePickerInput
from .models import Client
from django import forms

class ClientForm(forms.ModelForm):
	class Meta:
		model = Client
		fields = ('first_name','last_name','birth_date', 'phone')
		widgets = {
			'birth_date' : DatePickerInput(
				options={
                    "format": "DD/MM/YYYY", # moment date-time format
                    "showClose": True,
                    "showClear": True,
                    "showTodayButton": True,
                    "locale": "ru",
                }
				),
		}

coupons/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.template import Context, loader
from .models import Coupon
from .forms import ClientForm

def index(request):
	return render(request,'index.html')

def show(request):
	query = request.POST.get('q', None)
	try:
		c = Coupon.objects.get(code=query)
		if c.active:
			ctxt = {'coup': c }
			return render(request,'show.html',ctxt)	
		elif not c.active:
			context = {
			'message' : 'КОД уже активирован!!!'
			}
			return render(request, 'messages.html', context)
	except:
		context = {
		'message' : 'Такого КОДа не существует!'
		}
		return render(request, 'messages.html', context)
	

def activate(request):
	query = request.POST.get('q', None)
	c = Coupon.objects.get(code=query)
	c.active = False
	c.save()
	context = {
		'message' : 'КОД успешно активирован!'
	}
	return render(request, 'messages.html', context)

	

def signup(request):
	if request.method == 'POST':
		form = ClientForm(request.POST)
		if form.is_valid():

			form.save()
			context = {
			'message' : 'Номер успешно зарегистрирован!'
		}
		return render(request, 'messages.html', context)
	else:
		form = ClientForm()
		return render(request,'signup.html', {'form':form})

coupons/templates/base.html
<!doctype html>
<html lang="en">
  <head>
{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{% block extrahead %}       {# Extra Resources Start #}
{% endblock %}

  <title>ЭЛЕГАНТ</title>
  </head>
  <body>
    <div class="container d-flex h-100">
      <div class="row justify-content-center">
        <div>
          <h1> ЭЛЕГАНТ КУПОНЫ</h1>
          {% block main %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

coupons/templates/index.html
{% extends 'base.html' %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% block main %}
{% load crispy_forms_tags %}
<form method="POST" action="{% url 'coupons:show' %}" id="searchform">
	{% csrf_token %}
    {{ form|crispy }}
    <input class="searchfield" id="searchbox" name="q" type="text" value="{{ request.GET.q }}" placeholder="ВВЕДИТЕ КОД КУПОНА"/>
  
        <button type="submit" class="btn btn-primary">Проверить</button>
  
</form>
<a href="/coupons/signup" class="btn btn-success">Зарегистрироваться</a>  
{% endblock %}

coupons/templates/messages.html
{% extends 'base.html' %}
{% block main %}
{{ message }}
<a href="/" class="btn btn-success">Вернуться на главную</a>  
{% endblock %}

coupons/templates/show.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}

<div class='card'>
<div class="card-body">
<h2 class="card-title">{{ coup.promotion }} :: {{ coup.code }}</h2>
<p>Клиент: {{ coup.client }}</p>
<p>Телефон: {{ coup.client.phone }}</p>
<p>Email: {{ coup.client.email }}</p>

<form method="POST" action="{% url 'coupons:activate' %}" id="activate">
	{% csrf_token %}
    <input type="hidden" name="q" value="{{ coup.code }}">
    <button type="submit" class="btn btn-primary">Активировать</button>
	<a href="/" class="btn btn-warning">Назад</a>  
</form>
</div>
</div>

{% endblock %}

coupons/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block extrahead %}
{{ form.media }}
{% endblock %}
{% block main %}
{% load crispy_forms_tags %}
<form action="{% url 'coupons:signup' %}" method="post">
    {% csrf_token %}

    {{ form|crispy }}
    <input type="submit" value="Отправить">
</form>
{% endblock %}

coupons/templates/success.html
{% extends 'base.html' %}

{% block main %}
Все прошло успешно
<a href="/" class="btn btn-success">Вернуться на главную</a>  
{% endblock %}